//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.23 at 11:11:21 AM EST 
//


package com.capgemini.job.portal.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="candidateStatus">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="candidateStatusId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="candidateStatusName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "candidateStatus"
})
@XmlRootElement(name = "candidateStatuses")
public class CandidateStatuses {

    protected List<CandidateStatuses.CandidateStatus> candidateStatus;

    /**
     * Gets the value of the candidateStatus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the candidateStatus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCandidateStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CandidateStatuses.CandidateStatus }
     * 
     * 
     */
    public List<CandidateStatuses.CandidateStatus> getCandidateStatus() {
        if (candidateStatus == null) {
            candidateStatus = new ArrayList<CandidateStatuses.CandidateStatus>();
        }
        return this.candidateStatus;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="candidateStatusId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="candidateStatusName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "candidateStatusId",
        "candidateStatusName"
    })
    public static class CandidateStatus {

        protected String candidateStatusId;
        protected String candidateStatusName;

        /**
         * Gets the value of the candidateStatusId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCandidateStatusId() {
            return candidateStatusId;
        }

        /**
         * Sets the value of the candidateStatusId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCandidateStatusId(String value) {
            this.candidateStatusId = value;
        }

        /**
         * Gets the value of the candidateStatusName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCandidateStatusName() {
            return candidateStatusName;
        }

        /**
         * Sets the value of the candidateStatusName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCandidateStatusName(String value) {
            this.candidateStatusName = value;
        }

    }

}
