//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.23 at 10:46:34 AM EST 
//


package com.capgemini.job.portal.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="interviewStatus">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="interviewStatusId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="interviewStatusName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "interviewStatus"
})
@XmlRootElement(name = "interviewStatuses")
public class InterviewStatuses {

    protected List<InterviewStatuses.InterviewStatus> interviewStatus;

    /**
     * Gets the value of the interviewStatus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interviewStatus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInterviewStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InterviewStatuses.InterviewStatus }
     * 
     * 
     */
    public List<InterviewStatuses.InterviewStatus> getInterviewStatus() {
        if (interviewStatus == null) {
            interviewStatus = new ArrayList<InterviewStatuses.InterviewStatus>();
        }
        return this.interviewStatus;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="interviewStatusId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="interviewStatusName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "interviewStatusId",
        "interviewStatusName"
    })
    public static class InterviewStatus {

        protected String interviewStatusId;
        protected String interviewStatusName;

        /**
         * Gets the value of the interviewStatusId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInterviewStatusId() {
            return interviewStatusId;
        }

        /**
         * Sets the value of the interviewStatusId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInterviewStatusId(String value) {
            this.interviewStatusId = value;
        }

        /**
         * Gets the value of the interviewStatusName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInterviewStatusName() {
            return interviewStatusName;
        }

        /**
         * Sets the value of the interviewStatusName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInterviewStatusName(String value) {
            this.interviewStatusName = value;
        }

    }

}
