//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.09 at 10:09:10 AM EST 
//


package com.capgemini.job.portal.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="resume" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contractorRate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="primarySkills" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="buLeadApproval" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="capabilityLeadApproval" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="offerDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="offerAcceptDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="joiningDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="actualJoiningDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="resourceTypeId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="candidateStatusId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="candidateCategoryId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="citizenshipStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "resume",
    "contractorRate",
    "primarySkills",
    "buLeadApproval",
    "capabilityLeadApproval",
    "offerDate",
    "offerAcceptDate",
    "joiningDate",
    "actualJoiningDate",
    "resourceTypeId",
    "candidateStatusId",
    "candidateCategoryId",
    "citizenshipStatusId"
})
@XmlRootElement(name = "jobCandidate")
public class JobCandidate {

    protected String name;
    protected String resume;
    protected String contractorRate;
    protected String primarySkills;
    protected String buLeadApproval;
    protected String capabilityLeadApproval;
    protected String offerDate;
    protected String offerAcceptDate;
    protected String joiningDate;
    protected String actualJoiningDate;
    protected String resourceTypeId;
    protected String candidateStatusId;
    protected String candidateCategoryId;
    protected String citizenshipStatusId;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the resume property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResume() {
        return resume;
    }

    /**
     * Sets the value of the resume property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResume(String value) {
        this.resume = value;
    }

    /**
     * Gets the value of the contractorRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractorRate() {
        return contractorRate;
    }

    /**
     * Sets the value of the contractorRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractorRate(String value) {
        this.contractorRate = value;
    }

    /**
     * Gets the value of the primarySkills property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimarySkills() {
        return primarySkills;
    }

    /**
     * Sets the value of the primarySkills property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimarySkills(String value) {
        this.primarySkills = value;
    }

    /**
     * Gets the value of the buLeadApproval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuLeadApproval() {
        return buLeadApproval;
    }

    /**
     * Sets the value of the buLeadApproval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuLeadApproval(String value) {
        this.buLeadApproval = value;
    }

    /**
     * Gets the value of the capabilityLeadApproval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapabilityLeadApproval() {
        return capabilityLeadApproval;
    }

    /**
     * Sets the value of the capabilityLeadApproval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapabilityLeadApproval(String value) {
        this.capabilityLeadApproval = value;
    }

    /**
     * Gets the value of the offerDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferDate() {
        return offerDate;
    }

    /**
     * Sets the value of the offerDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferDate(String value) {
        this.offerDate = value;
    }

    /**
     * Gets the value of the offerAcceptDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferAcceptDate() {
        return offerAcceptDate;
    }

    /**
     * Sets the value of the offerAcceptDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferAcceptDate(String value) {
        this.offerAcceptDate = value;
    }

    /**
     * Gets the value of the joiningDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJoiningDate() {
        return joiningDate;
    }

    /**
     * Sets the value of the joiningDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJoiningDate(String value) {
        this.joiningDate = value;
    }

    /**
     * Gets the value of the actualJoiningDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActualJoiningDate() {
        return actualJoiningDate;
    }

    /**
     * Sets the value of the actualJoiningDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActualJoiningDate(String value) {
        this.actualJoiningDate = value;
    }

    /**
     * Gets the value of the resourceTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceTypeId() {
        return resourceTypeId;
    }

    /**
     * Sets the value of the resourceTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceTypeId(String value) {
        this.resourceTypeId = value;
    }

    /**
     * Gets the value of the candidateStatusId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCandidateStatusId() {
        return candidateStatusId;
    }

    /**
     * Sets the value of the candidateStatusId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCandidateStatusId(String value) {
        this.candidateStatusId = value;
    }

    /**
     * Gets the value of the candidateCategoryId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCandidateCategoryId() {
        return candidateCategoryId;
    }

    /**
     * Sets the value of the candidateCategoryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCandidateCategoryId(String value) {
        this.candidateCategoryId = value;
    }

    /**
     * Gets the value of the citizenshipStatusId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCitizenshipStatusId() {
        return citizenshipStatusId;
    }

    /**
     * Sets the value of the citizenshipStatusId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCitizenshipStatusId(String value) {
        this.citizenshipStatusId = value;
    }

}
