//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.23 at 10:40:46 AM EST 
//


package com.capgemini.job.portal.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="jobStatus">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="jobStatusId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="jobStatusName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "jobStatus"
})

public class JobStatuses {

    protected List<JobStatuses.JobStatus> jobStatus;

    /**
     * Gets the value of the jobStatus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jobStatus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJobStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JobStatuses.JobStatus }
     * 
     * 
     */
    public List<JobStatuses.JobStatus> getJobStatus() {
        if (jobStatus == null) {
            jobStatus = new ArrayList<JobStatuses.JobStatus>();
        }
        return this.jobStatus;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="jobStatusId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="jobStatusName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "jobStatusId",
        "jobStatusName"
    })
    public static class JobStatus {

        protected String jobStatusId;
        protected String jobStatusName;

        /**
         * Gets the value of the jobStatusId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJobStatusId() {
            return jobStatusId;
        }

        /**
         * Sets the value of the jobStatusId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJobStatusId(String value) {
            this.jobStatusId = value;
        }

        /**
         * Gets the value of the jobStatusName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJobStatusName() {
            return jobStatusName;
        }

        /**
         * Sets the value of the jobStatusName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJobStatusName(String value) {
            this.jobStatusName = value;
        }

    }

}
