//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.23 at 10:42:59 AM EST 
//


package com.capgemini.job.portal.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="jobStage">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="jobStageId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="jobStageName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "jobStage"
})
public class JobStages {

    protected List<JobStages.JobStage> jobStage;

    /**
     * Gets the value of the jobStage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jobStage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJobStage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JobStages.JobStage }
     * 
     * 
     */
    public List<JobStages.JobStage> getJobStage() {
        if (jobStage == null) {
            jobStage = new ArrayList<JobStages.JobStage>();
        }
        return this.jobStage;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="jobStageId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="jobStageName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "jobStageId",
        "jobStageName"
    })
    public static class JobStage {

        protected String jobStageId;
        protected String jobStageName;

        /**
         * Gets the value of the jobStageId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJobStageId() {
            return jobStageId;
        }

        /**
         * Sets the value of the jobStageId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJobStageId(String value) {
            this.jobStageId = value;
        }

        /**
         * Gets the value of the jobStageName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJobStageName() {
            return jobStageName;
        }

        /**
         * Sets the value of the jobStageName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJobStageName(String value) {
            this.jobStageName = value;
        }

    }

}
